/**
 * SIM-TKD - Daftar Bank Indonesia
 * ============================================
 * Sumber: https://github.com/riod94/list-bank-indonesia (bank.json)
 * Daftar bank yang tersedia di Indonesia (nama + kode bank).
 */
var DAFTAR_BANK = [
    {"name":"Bank Rakyat Indonesia (BRI)","code":"002"},
    {"name":"Bank Mandiri","code":"008"},
    {"name":"Bank Negara Indonesia (BNI)","code":"009"},
    {"name":"Bank Tabunngan Negara (BTN)","code":"200"},
    {"name":"Bank Central Asia (BCA)","code":"014"},
    {"name":"Bank BCA Syariah","code":"536"},
    {"name":"Bank Syariah Indonesia (BSI)","code":"451"},
    {"name":"Bank Tabungan Pensiun Nasional (BTPN)","code":"213"},
    {"name":"Bank Tabungan Pensiun Nasional Syariah (BTPN Syariah)","code":"547"},
    {"name":"Link Aja","code":"911"},
    {"name":"Indosat Dompetku","code":"789"},
    {"name":"Bank Aladin","code":"947"},
    {"name":"Bank Bukopin Syariah","code":"521"},
    {"name":"Bank Jabar Banten Syariah (bjb Syariah)","code":"425"},
    {"name":"Bank Muamalat","code":"147"},
    {"name":"Bank Panin Dubai Syariah","code":"517"},
    {"name":"Bank Mega Syariah","code":"506"},
    {"name":"Citibank","code":"031"},
    {"name":"Bank ANZ","code":"061"},
    {"name":"Bank Capital","code":"054"},
    {"name":"Bank Commonwealth","code":"950"},
    {"name":"Bank DBS","code":"046"},
    {"name":"Bank HSBC","code":"087"},
    {"name":"Bank IBK","code":"945"},
    {"name":"Bank of China","code":"069"},
    {"name":"Bank Shinhan","code":"152"},
    {"name":"Bank Woori Saudara","code":"212"},
    {"name":"Standard Chartered","code":"050"},
    {"name":"Bank BJB","code":"110"},
    {"name":"Bank DKI","code":"111"},
    {"name":"Bank BPD D.I.Y","code":"112"},
    {"name":"Bank Jateng","code":"113"},
    {"name":"Bank Jatim","code":"114"},
    {"name":"Bank Jambi","code":"115"},
    {"name":"Bank Aceh","code":"116"},
    {"name":"Bank Sumut","code":"117"},
    {"name":"Bank Nagari (Sumbar)","code":"118"},
    {"name":"Bank BRKSyariah (Bank Riau Kepri)","code":"119"},
    {"name":"Bank Sumsel and Babel","code":"120"},
    {"name":"Bank BPR Eka Bumi Artha","code":"867"},
    {"name":"Bank BPR Danagung Abadi","code":"028"},
    {"name":"Bank BPR Danagung Bakti","code":"028"},
    {"name":"Bank BPR Danagung Ramulti","code":"028"},
    {"name":"Bank BPR Karyajatnika Sadaya","code":"688"},
    {"name":"Bank BPR Supra Artapersada","code":"600"},
    {"name":"Allo Bank","code":"567"},
    {"name":"Bank Bumi Arta","code":"076"},
    {"name":"Bank CIMB Niaga","code":"022"},
    {"name":"Bank Danamon","code":"011"},
    {"name":"Bank Ganesha","code":"161"},
    {"name":"Bank ICBC Indonesia","code":"164"},
    {"name":"Bank Ina Perdana","code":"513"},
    {"name":"Bank Index Selindo","code":"555"},
    {"name":"Bank Jago","code":"542"},
    {"name":"Bank Jtrust","code":"095"},
    {"name":"Bank KB Bukopin.","code":"441"},
    {"name":"Bank KEB Hana","code":"484"},
    {"name":"Bank Mandiri Taspen Pos","code":"564"},
    {"name":"Bank Maybank Indonesia","code":"016"},
    {"name":"Bank Mayora","code":"553"},
    {"name":"Bank Mega","code":"426"},
    {"name":"Bank Mestika Dharma","code":"151"},
    {"name":"Bank MNC Internasional Tbk","code":"485"},
    {"name":"Bank National Nobu","code":"503"},
    {"name":"Bank Neo Commerce","code":"490"},
    {"name":"Bank OCBC NISP","code":"028"},
    {"name":"Bank of India Indonesia","code":"146"},
    {"name":"Bank Oke Indonesia","code":"526"},
    {"name":"Bank Panin","code":"019"},
    {"name":"Bank Permata","code":"013"},
    {"name":"Bank QNB Indonesia","code":"167"},
    {"name":"Bank Raya","code":"494"},
    {"name":"Bank Sahabat Sampoerna","code":"523"},
    {"name":"Bank Seabank Indonesia","code":"535"},
    {"name":"Bank Sinarmas","code":"153"},
    {"name":"Bank Tabungan Pensiunan Nasional","code":"213"},
    {"name":"Bank UOB Indonesia","code":"023"},
    {"name":"Altopay","code":"700"},
    {"name":"Bank Artha Graha","code":"037"},
    {"name":"Bank Chinatrust Indonesia","code":"949"},
    {"name":"Bank Jasa Jakarta","code":"472"},
    {"name":"Bank Maspion","code":"157"},
    {"name":"Bank BCA Digital (Bank Royal)","code":"501"},
    {"name":"Bank SBI Indonesia (Indomonex)","code":"498"},
    {"name":"Bank Victoria International","code":"566"},
    {"name":"Bank CNB","code":"559"},
    {"name":"Bank Harda International","code":"567"},
    {"name":"Bank MUFG","code":"042"},
    {"name":"Amar Bank","code":"531"},
    {"name":"Bank Banten","code":"137"},
    {"name":"Bank BPD Bali","code":"129"},
    {"name":"Bank CCB Indonesia","code":"036"},
    {"name":"Bank Kalbar","code":"123"},
    {"name":"Bank Kaltimtara","code":"124"},
    {"name":"Bank Kalteng","code":"125"},
    {"name":"Bank Maluku Malut","code":"131"},
    {"name":"Bank Mayapada","code":"097"},
    {"name":"Bank Murtiarta Sentosa","code":"548"},
    {"name":"Bank Papua","code":"132"},
    {"name":"Bank Sulsebar","code":"126"},
    {"name":"Bank Victoria Syariah","code":"405"},
    {"name":"Prima Master Bank","code":"520"},
];
