/**
 * SIM-TKD - Daftar Kota/Kabupaten Indonesia (LENGKAP - 514 kab/kota, 38 provinsi)
 * ============================================
 * Sumber: BPS/Kemendagri (wilayah-indonesia-bps, data 2025).
 * Pemetaan Kota/Kabupaten -> Provinsi. Dipakai di daftar.html & modul AKLAP.
 */
var DAFTAR_KOTA = [
    { kota: "Kabupaten Aceh Barat", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Barat Daya", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Besar", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Jaya", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Selatan", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Singkil", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Tamiang", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Tengah", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Tenggara", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Timur", provinsi: "Aceh" },
    { kota: "Kabupaten Aceh Utara", provinsi: "Aceh" },
    { kota: "Kabupaten Bener Meriah", provinsi: "Aceh" },
    { kota: "Kabupaten Bireuen", provinsi: "Aceh" },
    { kota: "Kabupaten Gayo Lues", provinsi: "Aceh" },
    { kota: "Kabupaten Nagan Raya", provinsi: "Aceh" },
    { kota: "Kabupaten Pidie", provinsi: "Aceh" },
    { kota: "Kabupaten Pidie Jaya", provinsi: "Aceh" },
    { kota: "Kabupaten Simeulue", provinsi: "Aceh" },
    { kota: "Kota Banda Aceh", provinsi: "Aceh" },
    { kota: "Kota Langsa", provinsi: "Aceh" },
    { kota: "Kota Lhokseumawe", provinsi: "Aceh" },
    { kota: "Kota Sabang", provinsi: "Aceh" },
    { kota: "Kota Subulussalam", provinsi: "Aceh" },
    { kota: "Kabupaten Badung", provinsi: "Bali" },
    { kota: "Kabupaten Bangli", provinsi: "Bali" },
    { kota: "Kabupaten Buleleng", provinsi: "Bali" },
    { kota: "Kabupaten Gianyar", provinsi: "Bali" },
    { kota: "Kabupaten Jembrana", provinsi: "Bali" },
    { kota: "Kabupaten Karangasem", provinsi: "Bali" },
    { kota: "Kabupaten Klungkung", provinsi: "Bali" },
    { kota: "Kabupaten Tabanan", provinsi: "Bali" },
    { kota: "Kota Denpasar", provinsi: "Bali" },
    { kota: "Kabupaten Lebak", provinsi: "Banten" },
    { kota: "Kabupaten Pandeglang", provinsi: "Banten" },
    { kota: "Kabupaten Serang", provinsi: "Banten" },
    { kota: "Kabupaten Tangerang", provinsi: "Banten" },
    { kota: "Kota Cilegon", provinsi: "Banten" },
    { kota: "Kota Serang", provinsi: "Banten" },
    { kota: "Kota Tangerang", provinsi: "Banten" },
    { kota: "Kota Tangerang Selatan", provinsi: "Banten" },
    { kota: "Kabupaten Bengkulu Selatan", provinsi: "Bengkulu" },
    { kota: "Kabupaten Bengkulu Tengah", provinsi: "Bengkulu" },
    { kota: "Kabupaten Bengkulu Utara", provinsi: "Bengkulu" },
    { kota: "Kabupaten Kaur", provinsi: "Bengkulu" },
    { kota: "Kabupaten Kepahiang", provinsi: "Bengkulu" },
    { kota: "Kabupaten Lebong", provinsi: "Bengkulu" },
    { kota: "Kabupaten Mukomuko", provinsi: "Bengkulu" },
    { kota: "Kabupaten Rejang Lebong", provinsi: "Bengkulu" },
    { kota: "Kabupaten Seluma", provinsi: "Bengkulu" },
    { kota: "Kota Bengkulu", provinsi: "Bengkulu" },
    { kota: "Kabupaten Bantul", provinsi: "Di Yogyakarta" },
    { kota: "Kabupaten Gunungkidul", provinsi: "Di Yogyakarta" },
    { kota: "Kabupaten Kulon Progo", provinsi: "Di Yogyakarta" },
    { kota: "Kabupaten Sleman", provinsi: "Di Yogyakarta" },
    { kota: "Kota Yogyakarta", provinsi: "Di Yogyakarta" },
    { kota: "Kabupaten Administrasi Kepulauan Seribu", provinsi: "Dki Jakarta" },
    { kota: "Kota Administrasi Jakarta Barat", provinsi: "Dki Jakarta" },
    { kota: "Kota Administrasi Jakarta Pusat", provinsi: "Dki Jakarta" },
    { kota: "Kota Administrasi Jakarta Selatan", provinsi: "Dki Jakarta" },
    { kota: "Kota Administrasi Jakarta Timur", provinsi: "Dki Jakarta" },
    { kota: "Kota Administrasi Jakarta Utara", provinsi: "Dki Jakarta" },
    { kota: "Kabupaten Boalemo", provinsi: "Gorontalo" },
    { kota: "Kabupaten Bone Bolango", provinsi: "Gorontalo" },
    { kota: "Kabupaten Gorontalo", provinsi: "Gorontalo" },
    { kota: "Kabupaten Gorontalo Utara", provinsi: "Gorontalo" },
    { kota: "Kabupaten Pohuwato", provinsi: "Gorontalo" },
    { kota: "Kota Gorontalo", provinsi: "Gorontalo" },
    { kota: "Kabupaten  Kerinci", provinsi: "Jambi" },
    { kota: "Kabupaten  Merangin", provinsi: "Jambi" },
    { kota: "Kabupaten  Muaro Jambi", provinsi: "Jambi" },
    { kota: "Kabupaten Batanghari", provinsi: "Jambi" },
    { kota: "Kabupaten Bungo", provinsi: "Jambi" },
    { kota: "Kabupaten Sarolangun", provinsi: "Jambi" },
    { kota: "Kabupaten Tanjung Jabung Barat", provinsi: "Jambi" },
    { kota: "Kabupaten Tanjung Jabung Timur", provinsi: "Jambi" },
    { kota: "Kabupaten Tebo", provinsi: "Jambi" },
    { kota: "Kota Jambi", provinsi: "Jambi" },
    { kota: "Kota Sungai Penuh", provinsi: "Jambi" },
    { kota: "Kabupaten Bandung", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Bandung Barat", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Bekasi", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Bogor", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Ciamis", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Cianjur", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Cirebon", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Garut", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Indramayu", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Karawang", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Kuningan", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Majalengka", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Pangandaran", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Purwakarta", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Subang", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Sukabumi", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Sumedang", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Tasikmalaya", provinsi: "Jawa Barat" },
    { kota: "Kota Bandung", provinsi: "Jawa Barat" },
    { kota: "Kota Banjar", provinsi: "Jawa Barat" },
    { kota: "Kota Bekasi", provinsi: "Jawa Barat" },
    { kota: "Kota Bogor", provinsi: "Jawa Barat" },
    { kota: "Kota Cimahi", provinsi: "Jawa Barat" },
    { kota: "Kota Cirebon", provinsi: "Jawa Barat" },
    { kota: "Kota Depok", provinsi: "Jawa Barat" },
    { kota: "Kota Sukabumi", provinsi: "Jawa Barat" },
    { kota: "Kota Tasikmalaya", provinsi: "Jawa Barat" },
    { kota: "Kabupaten Banjarnegara", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Banyumas", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Batang", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Blora", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Boyolali", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Brebes", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Cilacap", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Demak", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Grobogan", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Jepara", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Karanganyar", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Kebumen", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Kendal", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Klaten", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Kudus", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Magelang", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Pati", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Pekalongan", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Pemalang", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Purbalingga", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Purworejo", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Rembang", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Semarang", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Sragen", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Sukoharjo", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Tegal", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Temanggung", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Wonogiri", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Wonosobo", provinsi: "Jawa Tengah" },
    { kota: "Kota Magelang", provinsi: "Jawa Tengah" },
    { kota: "Kota Pekalongan", provinsi: "Jawa Tengah" },
    { kota: "Kota Salatiga", provinsi: "Jawa Tengah" },
    { kota: "Kota Semarang", provinsi: "Jawa Tengah" },
    { kota: "Kota Surakarta", provinsi: "Jawa Tengah" },
    { kota: "Kota Tegal", provinsi: "Jawa Tengah" },
    { kota: "Kabupaten Bangkalan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Banyuwangi", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Blitar", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Bojonegoro", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Bondowoso", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Gresik", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Jember", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Jombang", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Kediri", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Lamongan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Lumajang", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Madiun", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Magetan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Malang", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Mojokerto", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Nganjuk", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Ngawi", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Pacitan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Pamekasan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Pasuruan", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Ponorogo", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Probolinggo", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Sampang", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Sidoarjo", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Situbondo", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Sumenep", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Trenggalek", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Tuban", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Tulungagung", provinsi: "Jawa Timur" },
    { kota: "Kota Batu", provinsi: "Jawa Timur" },
    { kota: "Kota Blitar", provinsi: "Jawa Timur" },
    { kota: "Kota Kediri", provinsi: "Jawa Timur" },
    { kota: "Kota Madiun", provinsi: "Jawa Timur" },
    { kota: "Kota Malang", provinsi: "Jawa Timur" },
    { kota: "Kota Mojokerto", provinsi: "Jawa Timur" },
    { kota: "Kota Pasuruan", provinsi: "Jawa Timur" },
    { kota: "Kota Probolinggo", provinsi: "Jawa Timur" },
    { kota: "Kota Surabaya", provinsi: "Jawa Timur" },
    { kota: "Kabupaten Bengkayang", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Kapuas Hulu", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Kayong Utara", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Ketapang", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Kubu Raya", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Landak", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Melawi", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Mempawah", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Sambas", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Sanggau", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Sekadau", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Sintang", provinsi: "Kalimantan Barat" },
    { kota: "Kota Pontianak", provinsi: "Kalimantan Barat" },
    { kota: "Kota Singkawang", provinsi: "Kalimantan Barat" },
    { kota: "Kabupaten Balangan", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Banjar", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Barito Kuala", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Hulu Sungai Selatan", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Hulu Sungai Tengah", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Hulu Sungai Utara", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Kotabaru", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Tabalong", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Tanah Bumbu", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Tanah Laut", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Tapin", provinsi: "Kalimantan Selatan" },
    { kota: "Kota Banjarbaru", provinsi: "Kalimantan Selatan" },
    { kota: "Kota Banjarmasin", provinsi: "Kalimantan Selatan" },
    { kota: "Kabupaten Barito Selatan", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Barito Timur", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Barito Utara", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Gunung Mas", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Kapuas", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Katingan", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Kotawaringin Barat", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Kotawaringin Timur", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Lamandau", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Murung Raya", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Pulang Pisau", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Seruyan", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Sukamara", provinsi: "Kalimantan Tengah" },
    { kota: "Kota Palangkaraya", provinsi: "Kalimantan Tengah" },
    { kota: "Kabupaten Berau", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Kutai Barat", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Kutai Kartanegara", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Kutai Timur", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Mahakam Ulu", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Paser", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Penajam Paser Utara", provinsi: "Kalimantan Timur" },
    { kota: "Kota Balikpapan", provinsi: "Kalimantan Timur" },
    { kota: "Kota Bontang", provinsi: "Kalimantan Timur" },
    { kota: "Kota Samarinda", provinsi: "Kalimantan Timur" },
    { kota: "Kabupaten Bulungan", provinsi: "Kalimantan Utara" },
    { kota: "Kabupaten Malinau", provinsi: "Kalimantan Utara" },
    { kota: "Kabupaten Nunukan", provinsi: "Kalimantan Utara" },
    { kota: "Kabupaten Tana Tidung", provinsi: "Kalimantan Utara" },
    { kota: "Kota Tarakan", provinsi: "Kalimantan Utara" },
    { kota: "Kabupaten Bangka", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Bangka Barat", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Bangka Selatan", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Bangka Tengah", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Belitung", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Belitung Timur", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kota Pangkal Pinang", provinsi: "Kepulauan Bangka Belitung" },
    { kota: "Kabupaten Bintan", provinsi: "Kepulauan Riau" },
    { kota: "Kabupaten Karimun", provinsi: "Kepulauan Riau" },
    { kota: "Kabupaten Kepulauan Anambas", provinsi: "Kepulauan Riau" },
    { kota: "Kabupaten Lingga", provinsi: "Kepulauan Riau" },
    { kota: "Kabupaten Natuna", provinsi: "Kepulauan Riau" },
    { kota: "Kota Batam", provinsi: "Kepulauan Riau" },
    { kota: "Kota Tanjung Pinang", provinsi: "Kepulauan Riau" },
    { kota: "Kabupaten Lampung Barat", provinsi: "Lampung" },
    { kota: "Kabupaten Lampung Selatan", provinsi: "Lampung" },
    { kota: "Kabupaten Lampung Tengah", provinsi: "Lampung" },
    { kota: "Kabupaten Lampung Timur", provinsi: "Lampung" },
    { kota: "Kabupaten Lampung Utara", provinsi: "Lampung" },
    { kota: "Kabupaten Mesuji", provinsi: "Lampung" },
    { kota: "Kabupaten Pesawaran", provinsi: "Lampung" },
    { kota: "Kabupaten Pesisir Barat", provinsi: "Lampung" },
    { kota: "Kabupaten Pringsewu", provinsi: "Lampung" },
    { kota: "Kabupaten Tanggamus", provinsi: "Lampung" },
    { kota: "Kabupaten Tulang Bawang", provinsi: "Lampung" },
    { kota: "Kabupaten Tulang Bawang Barat", provinsi: "Lampung" },
    { kota: "Kabupaten Way Kanan", provinsi: "Lampung" },
    { kota: "Kota Bandar Lampung", provinsi: "Lampung" },
    { kota: "Kota Metro", provinsi: "Lampung" },
    { kota: "Kabupaten Buru", provinsi: "Maluku" },
    { kota: "Kabupaten Buru Selatan", provinsi: "Maluku" },
    { kota: "Kabupaten Kepulauan Aru", provinsi: "Maluku" },
    { kota: "Kabupaten Kepulauan Tanimbar", provinsi: "Maluku" },
    { kota: "Kabupaten Maluku Barat Daya", provinsi: "Maluku" },
    { kota: "Kabupaten Maluku Tengah", provinsi: "Maluku" },
    { kota: "Kabupaten Maluku Tenggara", provinsi: "Maluku" },
    { kota: "Kabupaten Seram Bagian Barat", provinsi: "Maluku" },
    { kota: "Kabupaten Seram Bagian Timur", provinsi: "Maluku" },
    { kota: "Kota Ambon", provinsi: "Maluku" },
    { kota: "Kota Tual", provinsi: "Maluku" },
    { kota: "Kabupaten Halmahera Barat", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Halmahera Selatan", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Halmahera Tengah", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Halmahera Timur", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Halmahera Utara", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Kepulauan Sula", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Pulau Morotai", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Pulau Taliabu", provinsi: "Maluku Utara" },
    { kota: "Kota Ternate", provinsi: "Maluku Utara" },
    { kota: "Kota Tidore Kepulauan", provinsi: "Maluku Utara" },
    { kota: "Kabupaten Bima", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Dompu", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Lombok Barat", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Lombok Tengah", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Lombok Timur", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Lombok Utara", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Sumbawa", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kabupaten Sumbawa Barat", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kota Bima", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kota Mataram", provinsi: "Nusa Tenggara Barat" },
    { kota: "Kab Timor Tengah Selatan", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Alor", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Belu", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Ende", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Flores Timur", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Kupang", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Lembata", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Malaka", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Manggarai", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Manggarai Barat", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Manggarai Timur", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Nagekeo", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Ngada", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Rote Ndao", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sabu Raijua", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sikka", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sumba Barat", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sumba Barat Daya", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sumba Tengah", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Sumba Timur", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Timor Tengah Utara", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kota Kupang", provinsi: "Nusa Tenggara Timur" },
    { kota: "Kabupaten Biak Numfor", provinsi: "Papua" },
    { kota: "Kabupaten Jayapura", provinsi: "Papua" },
    { kota: "Kabupaten Keerom", provinsi: "Papua" },
    { kota: "Kabupaten Kepulauan Yapen", provinsi: "Papua" },
    { kota: "Kabupaten Mamberamo Raya", provinsi: "Papua" },
    { kota: "Kabupaten Sarmi", provinsi: "Papua" },
    { kota: "Kabupaten Supiori", provinsi: "Papua" },
    { kota: "Kabupaten Waropen", provinsi: "Papua" },
    { kota: "Kota Jayapura", provinsi: "Papua" },
    { kota: "Kabupaten Fak Fak", provinsi: "Papua Barat" },
    { kota: "Kabupaten Kaimana", provinsi: "Papua Barat" },
    { kota: "Kabupaten Manokwari", provinsi: "Papua Barat" },
    { kota: "Kabupaten Manokwari Selatan", provinsi: "Papua Barat" },
    { kota: "Kabupaten Pegunungan Arfak", provinsi: "Papua Barat" },
    { kota: "Kabupaten Teluk Bintuni", provinsi: "Papua Barat" },
    { kota: "Kabupaten Teluk Wondama", provinsi: "Papua Barat" },
    { kota: "Kabupaten Maybrat", provinsi: "Papua Barat Daya" },
    { kota: "Kabupaten Raja Ampat", provinsi: "Papua Barat Daya" },
    { kota: "Kabupaten Sorong", provinsi: "Papua Barat Daya" },
    { kota: "Kabupaten Sorong Selatan", provinsi: "Papua Barat Daya" },
    { kota: "Kabupaten Tambrauw", provinsi: "Papua Barat Daya" },
    { kota: "Kota Sorong", provinsi: "Papua Barat Daya" },
    { kota: "Kab Pegunungan Bintang", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Jayawijaya", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Lanny Jaya", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Mamberamo Tengah", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Nduga", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Tolikara", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Yahukimo", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Yalimo", provinsi: "Papua Pegunungan" },
    { kota: "Kabupaten Asmat", provinsi: "Papua Selatan" },
    { kota: "Kabupaten Boven Digoel", provinsi: "Papua Selatan" },
    { kota: "Kabupaten Mappi", provinsi: "Papua Selatan" },
    { kota: "Kabupaten Merauke", provinsi: "Papua Selatan" },
    { kota: "Kabupaten Deiyai", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Dogiyai", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Intan Jaya", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Mimika", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Nabire", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Paniai", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Puncak", provinsi: "Papua Tengah" },
    { kota: "Kabupaten Puncak Jaya", provinsi: "Papua Tengah" },
    { kota: "Kabupaten  Pelalawan", provinsi: "Riau" },
    { kota: "Kabupaten  Rokan Hilir", provinsi: "Riau" },
    { kota: "Kabupaten  Rokan Hulu", provinsi: "Riau" },
    { kota: "Kabupaten Bengkalis", provinsi: "Riau" },
    { kota: "Kabupaten Indragiri Hilir", provinsi: "Riau" },
    { kota: "Kabupaten Indragiri Hulu", provinsi: "Riau" },
    { kota: "Kabupaten Kampar", provinsi: "Riau" },
    { kota: "Kabupaten Kepulauan Meranti", provinsi: "Riau" },
    { kota: "Kabupaten Kuantan Singingi", provinsi: "Riau" },
    { kota: "Kabupaten Siak", provinsi: "Riau" },
    { kota: "Kota Dumai", provinsi: "Riau" },
    { kota: "Kota Pekanbaru", provinsi: "Riau" },
    { kota: "Kabupaten Majene", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Mamasa", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Mamuju", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Mamuju Tengah", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Pasangkayu", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Polewali Mandar", provinsi: "Sulawesi Barat" },
    { kota: "Kabupaten Bantaeng", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Barru", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Bone", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Bulukumba", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Enrekang", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Gowa", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Jeneponto", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Kepulauan Selayar", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Luwu", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Luwu Timur", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Luwu Utara", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Maros", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Pangkajene Dan Kepulauan", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Pinrang", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Sidenreng Rappang", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Sinjai", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Soppeng", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Takalar", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Tana Toraja", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Toraja Utara", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Wajo", provinsi: "Sulawesi Selatan" },
    { kota: "Kota Makassar", provinsi: "Sulawesi Selatan" },
    { kota: "Kota Palopo", provinsi: "Sulawesi Selatan" },
    { kota: "Kota Parepare", provinsi: "Sulawesi Selatan" },
    { kota: "Kabupaten Banggai", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Banggai Kepulauan", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Banggai Laut", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Buol", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Donggala", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Morowali", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Morowali Utara", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Parigi Moutong", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Poso", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Sigi", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Tojo Una Una", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Toli-Toli", provinsi: "Sulawesi Tengah" },
    { kota: "Kota Palu", provinsi: "Sulawesi Tengah" },
    { kota: "Kabupaten Bombana", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Buton", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Buton Selatan", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Buton Tengah", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Buton Utara", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Kolaka", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Kolaka Timur", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Kolaka Utara", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Konawe", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Konawe Kepulauan", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Konawe Selatan", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Konawe Utara", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Muna", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Muna Barat", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Wakatobi", provinsi: "Sulawesi Tenggara" },
    { kota: "Kota Bau Bau", provinsi: "Sulawesi Tenggara" },
    { kota: "Kota Kendari", provinsi: "Sulawesi Tenggara" },
    { kota: "Kabupaten Bolaang Mongondow", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Bolaang Mongondow Selatan", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Bolaang Mongondow Timur", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Bolaang Mongondow Utara", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Kep. Siau Tagulandang Biaro", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Kepulauan Sangihe", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Kepulauan Talaud", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Minahasa", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Minahasa Selatan", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Minahasa Tenggara", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Minahasa Utara", provinsi: "Sulawesi Utara" },
    { kota: "Kota Bitung", provinsi: "Sulawesi Utara" },
    { kota: "Kota Kotamobagu", provinsi: "Sulawesi Utara" },
    { kota: "Kota Manado", provinsi: "Sulawesi Utara" },
    { kota: "Kota Tomohon", provinsi: "Sulawesi Utara" },
    { kota: "Kabupaten Agam", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Dharmasraya", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Kepulauan Mentawai", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Lima Puluh Kota", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Padang Pariaman", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Pasaman", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Pasaman Barat", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Pesisir Selatan", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Sijunjung", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Solok", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Solok Selatan", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Tanah Datar", provinsi: "Sumatera Barat" },
    { kota: "Kota Bukittinggi", provinsi: "Sumatera Barat" },
    { kota: "Kota Padang", provinsi: "Sumatera Barat" },
    { kota: "Kota Padang Panjang", provinsi: "Sumatera Barat" },
    { kota: "Kota Pariaman", provinsi: "Sumatera Barat" },
    { kota: "Kota Payakumbuh", provinsi: "Sumatera Barat" },
    { kota: "Kota Sawahlunto", provinsi: "Sumatera Barat" },
    { kota: "Kota Solok", provinsi: "Sumatera Barat" },
    { kota: "Kabupaten Banyuasin", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Empat Lawang", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Lahat", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Muara Enim", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Musi Banyuasin", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Musi Rawas", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Musi Rawas Utara", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Ogan Ilir", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Ogan Komering Ilir", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Ogan Komering Ulu", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Ogan Komering Ulu Selatan", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Ogan Komering Ulu Timur", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Penukal Abab Lematang Ilir", provinsi: "Sumatera Selatan" },
    { kota: "Kota Lubuk Linggau", provinsi: "Sumatera Selatan" },
    { kota: "Kota Pagar Alam", provinsi: "Sumatera Selatan" },
    { kota: "Kota Palembang", provinsi: "Sumatera Selatan" },
    { kota: "Kota Prabumulih", provinsi: "Sumatera Selatan" },
    { kota: "Kabupaten Asahan", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Batu Bara", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Dairi", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Deli Serdang", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Humbang Hasundutan", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Karo", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Labuhanbatu", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Labuhanbatu Selatan", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Labuhanbatu Utara", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Langkat", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Mandailing Natal", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Nias", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Nias Barat", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Nias Selatan", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Nias Utara", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Padang Lawas", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Padang Lawas Utara", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Pakpak Bharat", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Samosir", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Serdang Bedagai", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Simalungun", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Tapanuli Selatan", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Tapanuli Tengah", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Tapanuli Utara", provinsi: "Sumatera Utara" },
    { kota: "Kabupaten Toba", provinsi: "Sumatera Utara" },
    { kota: "Kota Binjai", provinsi: "Sumatera Utara" },
    { kota: "Kota Gunungsitoli", provinsi: "Sumatera Utara" },
    { kota: "Kota Medan", provinsi: "Sumatera Utara" },
    { kota: "Kota Padangsidimpuan", provinsi: "Sumatera Utara" },
    { kota: "Kota Pematangsiantar", provinsi: "Sumatera Utara" },
    { kota: "Kota Sibolga", provinsi: "Sumatera Utara" },
    { kota: "Kota Tanjungbalai", provinsi: "Sumatera Utara" },
    { kota: "Kota Tebing Tinggi", provinsi: "Sumatera Utara" },
];

/**
 * Ambil provinsi dari nama kota/kabupaten.
 * @param {string} kota
 * @returns {string}
 */
function getProvinsi(kota) {
    var name = String(kota || '').trim().toLowerCase();
    if (!name) return '';
    for (var i = 0; i < DAFTAR_KOTA.length; i++) {
        if (DAFTAR_KOTA[i].kota.toLowerCase() === name) {
            return DAFTAR_KOTA[i].provinsi;
        }
    }
    return '';
}
